spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/polygon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useAffectedRows=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 60MB
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    #开启发送失败退回
    publisher-returns: true
    #开启发送确认
    publisher-confirm-type: correlated
    port: 5672
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 123456
  cache:
    cache-names: department_cache,menu_cache


server:
  port: 8082


custom:
  path: D:/polygon
  initial-password: '{noop}123456'

mybatis:
  config-location: classpath:/mybatis-config.xml
logging:
  file:
    name: D:/polygon/log/polygonLog.log

