server:
  port: 8083

spring:
  mail:
    host: smtp.163.com
    protocol: smtps
    default-encoding: UTF-8
    password:
    username: 
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    from: ''

  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        #消费者消费消息成功以后需手动进行签收
        acknowledge-mode: manual
        prefetch: 100
